[tool.poetry]
name = "poetry-templating"
version = "0.1.0"
description = "A plugin for poetry which lets you substitute text on build."
authors = ["NimajnebEC <nimajnebec@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "poetry_templating", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8.1"
poetry = "^1.6.0"

[tool.poetry.group.dev.dependencies]
flake8-length = "^0.3.1"
black = "^23.10.0"
flake8 = "^6.1.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."poetry.application.plugin"]
templating = "poetry_templating.plugin:TemplatingPlugin"

[tool.poetry_templating]
exclude = "src/poetry_templating/engine.py"
